# Generated by Django 3.1.3 on 2020-11-16 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='addressEN',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='nameEN',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='addressZH',
        ),
        migrations.RemoveField(
            model_name='location',
            name='nameZH',
        ),
    ]
