# Generated by Django 3.1.3 on 2020-11-16 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_auto_20201116_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(default=0)),
                ('date_confirmed', models.DateField()),
                ('local', models.CharField(default='local', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Virus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('common_name', models.CharField(max_length=200)),
                ('max_inf_period', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CaseLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('category', models.CharField(choices=[('1', 'Residence'), ('2', 'Workplace'), ('3', 'Visit')], default='Residence', max_length=50)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.location')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.patient'),
        ),
        migrations.AddField(
            model_name='case',
            name='virus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.virus'),
        ),
    ]
