# Generated by Django 3.1.3 on 2020-11-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='hkid',
            field=models.CharField(default='---', max_length=20),
        ),
        migrations.AlterField(
            model_name='case',
            name='local',
            field=models.CharField(choices=[('1', 'local'), ('2', 'imported')], default='local', max_length=10),
        ),
    ]
