# Generated by Django 3.1.2 on 2020-11-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20201116_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='local',
            field=models.CharField(choices=[('1', 'Local'), ('2', 'Imported')], default='Local', max_length=10),
        ),
    ]
